# skype setting
host : '192.168.1.37'
port : 20000
me : 'shokaishokai'
chat : 'chat-id'
source_users :
  - 'shokaishokai'
  - 'shokai_bot'

# mongo db setting
mongo_host : 'localhost'
mongo_port : 27017
mongo_dbname : 'skype'
